hello_alps/urls.py
from .import views
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import Login, register, user_reservation

urlpatterns = [
    path('', views.index, name='index'),
    path('menu_list', views.MenuList.as_view(), name='menu_list'),
    path('opening_hours', views.OpeningHour, name='opening_hours'),
    path('reservations/', views.reservations, name='reservations'),
    path('login/', Login.as_view(), name='login_url'),
    path('register/', register, name='signup_url'),
    path('guest_reservation/', views.guest_reservation,
         name='guest_reservation'),
    path('user_reservation/', views.user_reservation, name='user_reservation'),
    path('about/', views.about_me, name='about'),
    path('contact/', views.contact, name='contact'),
    path('user_reservations/', views.user_reservations,
         name='user_reservations'),
    path('edit_reservation/<int:reservation_id>/', views.edit_reservation,
         name='edit_reservation'),
    path('cancel_reservation/<int:reservation_id>/', views.cancel_reservation,
         name='cancel_reservation'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

our_restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from hello_alps import views as index_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("hello_alps.urls"), name="hello_alps-urls"),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls'))
]

hello_alps/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class Menu(models.Model):
    """ Manages the menu items """
    name = models.CharField(max_length=300, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    categories = models.CharField(max_length=50, choices=[
        ('starters', 'Starters'),
        ('maindishes', 'Main dishes'),
        ('pizza', 'Pizza'),
        ('desserts', 'Desserts'),
    ])

    def __str__(self):
        return self.name


class OpeningHour(models.Model):
    """ Manages the opening hours """
    day_of_week = models.CharField(choices=[
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
        ('Sunday', 'Sunday')
    ])
    open_time = models.TimeField()
    close_time = models.TimeField()

    class Meta:
        ordering = ['day_of_week']
        verbose_name = 'Opening Hour'
        verbose_name_plural = 'Opening Hours'

    def __str__(self):
        return f"{self.day_of_week}: {self.open_time} - {self.close_time}"


class Table(models.Model):
    table_number = models.PositiveIntegerField()
    capacity = models.PositiveIntegerField()
    status = models.CharField(choices=[
        ('available', 'Available'),
        ('reserved', 'Reserved'),
    ], default='available')

    class Meta:
        ordering = ['table_number']

    def __str__(self):
        return f"Table: {self.table_number} - Capacity: {self.capacity}"


class UserReservation(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, null=True, blank=True)
    table = models.ForeignKey('Table', on_delete=models.SET_NULL, null=True)
    date = models.DateField(default=timezone.now)
    opening_hour = models.ForeignKey('OpeningHour', on_delete=models.SET_NULL,
                                     null=True)
    time = models.TimeField()
    comment = models.TextField(blank=True, max_length=1000)

    class Meta:
        ordering = ['date', 'time']
        verbose_name = 'User Reservation'
        verbose_name_plural = 'User Reservations'

    def __str__(self):
        table_info = f"Table {self.table.table_number} (Capacity {self.table.capacity})" if self.table else "No table asigned"
        return f"{self.date} - {self.time} - {table_info}"


@receiver(post_save, sender=UserReservation)
def update_table_status(sender, instance, **kwargs):
    table = instance.table
    if kwargs.get('created', False):
        table.status = 'Reserved'
        table.save()


@receiver(post_save, sender=UserReservation)
def update_table_status_on_delete(sender, instance, **kwargs):
    if kwargs.get('created', False):
        reserved_tables = UserReservation.objects.filter(table=instance.table,
                                                         date=instance.date,
                                                         time=instance.time).exists()
        if not reserved_tables:
            instance.table.status = 'Available'
            instance.table.save()


class About(models.Model):
    title = models.CharField(max_length=200)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()

    def __str__(self):
        return self.title

hello_alps/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.db.models import Case, When, Value, IntegerField
from django.urls import reverse_lazy
from .models import Menu, OpeningHour, UserReservation, About
from .forms import FormCreation, UserReservationForm, GuestReservationForm
from datetime import datetime


# Create your views here.


# Homepage view
def index(request):
    # Add custom order to the days of the week
    ordering = Case(
        When(day_of_week='Monday', then=Value(1)),
        When(day_of_week='Tuesday', then=Value(2)),
        When(day_of_week='Wednesday', then=Value(3)),
        When(day_of_week='Thursday', then=Value(4)),
        When(day_of_week='Friday', then=Value(5)),
        When(day_of_week='Saturday', then=Value(6)),
        When(day_of_week='Sunday', then=Value(7)),
        output_field=IntegerField(),
    )
    opening_hours = OpeningHour.objects.annotate(day_order=ordering).order_by('day_order')
    return render(request,
                  'hello_alps/index.html', {'opening_hours': opening_hours})


# Menu List View
class MenuList(generic.ListView):
    context_object_name = 'sort_menu_items'
    template_name = 'hello_alps/menu_list.html'

    def get_queryset(self):
        ordered_categories = ['starters', 'maindishes', 'pizza', 'desserts']
        sort_menu_items = {category: Menu.objects.filter(categories=category)
                           for category in ordered_categories}
        return sort_menu_items


# Reservations.html View
def reservations(request):
    return render(request, 'hello_alps/reservations.html')


# guest_reservation.html View
def guest_reservation(request):
    if request.method == 'POST':
        form = GuestReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save()

            request.session['reservation_success'] = True
            request.session['reservation_date'] = reservation.date.strftime('%Y.%m.%d')
            request.session['reservation_time'] = reservation.time.strftime('%H:%M')

            return redirect('guest_reservation')
        else:
            return render(request,
                          'hello_alps/guest_reservation.html', {'form': form})

    else:
        form = GuestReservationForm()

    reservation_success = request.session.pop('reservation_success', False)
    reservation_date = request.session.pop('reservation_date', '')
    reservation_time = request.session.pop('reservation_time', '')

    return render(request, 'hello_alps/guest_reservation.html', {
        'form': form,
        'reservation_success': reservation_success,
        'reservation_date': reservation_date,
        'reservation_time': reservation_time,
        })


# user_reservation.html View
@login_required
def user_reservation(request):
    if request.method == 'POST':
        post_data = request.POST.copy()
        date_str = post_data.get('date')

        if date_str:
            formatted_date = datetime.strptime(date_str, '%Y-%m-%d').strftime('%Y-%m-%d')
            post_data['date'] = formatted_date

        if 'reservation_id' in request.POST:
            reservation = UserReservation.objects.get(pk=request.POST['reservation_id'])
            form = UserReservationForm(post_data, isinstance=reservation)

        form = UserReservationForm(post_data)

        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.user = request.user
            reservation.save()

            request.session['reservation_success'] = True
            request.session['reservation_date'] = reservation.date.strftime('%Y.%m.%d')
            request.session['reservation_time'] = reservation.time.strftime('%H:%M')

            return redirect('user_reservations')
        else:
            return render(request,
                          'hello_alps/user_reservation.html', {'form': form})

    else:
        form = UserReservationForm()

        if 'date' in request.GET:
            try:
                selected_date = datetime.strptime(request.GET['date'], '%Y-%m-%d').date()
                form.fields['time'].choices = form.get_time_choices(selected_date)
            except ValueError:
                messages.error(request, "Invalida date format.")

    return render(request, 'hello_alps/user_reservation.html', {'form': form})


# Reservation management
@login_required
def user_reservations(request):
    reservations = UserReservation.objects.filter(user=request.user,
                                                  date__gte=datetime.today()).order_by('date')

    # Retrieve session flags
    reservation_success = request.session.pop('reservation_success', False)
    edit_success = request.session.pop('edit_success', False)
    reservation_date = request.session.pop('reservation_date', None)
    reservation_time = request.session.pop('reservation_time', None)
    cancel_warning = request.session.pop('cancel_warning', False)

    return render(request, 'hello_alps/user_reservations.html', {
        'reservations': reservations,
        'reservation_success': reservation_success,
        'reservation_date': reservation_date,
        'reservation_time': reservation_time,
        'edit_success': edit_success,
        'cancel_warning': cancel_warning,
        })


# Edit reservation View
@login_required
def edit_reservation(request, reservation_id):
    reservation = get_object_or_404(UserReservation, id=reservation_id, user=request.user)

    if request.method == 'POST':
        form = UserReservationForm(request.POST, instance=reservation)
        if form.is_valid():
            updated_reservation = form.save()
            request.session['edit_success'] = True
            request.session['reservation_date'] = updated_reservation.date.strftime('%Y.%m.%d')
            request.session['reservation_time'] = updated_reservation.time.strftime('%H:%M')
            return redirect('user_reservations')
    else:
        form = UserReservationForm(instance=reservation)

    return render(request, 'hello_alps/edit_reservation.html', {
        'form': form,
        'reservation': reservation
        })


# Cancel reservation View
@login_required
def cancel_reservation(request, reservation_id):
    reservation = get_object_or_404(UserReservation,
                                    id=reservation_id, user=request.user)
    reservation.delete()
    request.session['cancel_warning'] = True
    return redirect('user_reservations')


# Login View
class Login(LoginView):
    template_name = 'hello_alps/login.html'
    success_url = reverse_lazy('home')


# Register View
def register(request):
    if request.method == 'POST':
        form = FormCreation(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('user_reservation')
    else:
        form = FormCreation()
    return render(request, 'hello_alps/register.html', {'form': form})


# About View
def about_me(request):
    about = About.objects.all().order_by('-updated_on').first()

    return render(
        request, "hello_alps/about.html", {"about": about},
    )


# contact.html View
def contact(request):
    return render(request, 'hello_alps/contact.html')

hello_alps/templates/hello_alps/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- about.html content starts here -->

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="row">
                <div class="col-11 col-md-4 ">
                    <img src="{% static 'images/family.jpg' %}" width="180" alt="family photo">
                </div>
                <div class="col-11 col-md-8  text-center">
                    <h2>{{ about.title }}</h2>
                    {{ about.content | safe }}
                </div>
            </div>
            <div class="row">
                <div class="col text-right">
                  <!-- Updated on field goes in here -->
            
                  <p class="text-end"><em>Updated on: {{ about.updated_on }}</em></p>
                </div>
              </div>            
        </div>
    </div>
</div>

<!-- about.html content ends here -->
{% endblock %}

hello_alps/templates/hello_alps/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- contact.html content starts here -->

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <h1 class="text-center">We are allways happy to see You!</h1>
            <hr>
            <h2 class="text-center">Visit us: Kolber 4 </h2>
            <hr>
            <h2 class="text-center">6235 Reith Im Alpbachtal</h2> 
            <hr>
            <h2 class="text-center">Call us: 0664321123</h2>
            <hr>
            <h2 class="text-center">Email us: ourrestaurant@gmail.com</h2>   
            <hr>
            <p class="text-center">Thank You for choosing our family restaurant!</p>    
        </div>
    </div>
</div>

<!-- contact.html content ends here -->
{% endblock %}

hello_alps/templates/hello_alps/edit_reservation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<!-- edit_reservation.html content starts here -->

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="user_reservation mt-5 mx-5">
                <h1 class="text-center">{{request.user}}, edit Your Reservation</h1>
                <hr>
                <div class="d-flex justify-content-center">
                    <form method="post" class="text-center col-md-8 col-lg-8 col-xl-7"
                        action="{% url 'edit_reservation' reservation.id %}">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-lg text-uppercase">Save Changes</button>
                    </form>
                </div>
                <p class="text-center">Thank You for choosing our family restaurant!</p>
            </div>
        </div>
    </div>
</div>

<!-- edit_reservation.html content ends here -->
{% endblock %}

hello_alps/templates/hello_alps/guest_reservation.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- guest_reservation.html content starts here -->

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="guest_reservation mt-5 mx-5">
                <h1 class="text-center">Make a Reservation</h1>
                <hr>
                <div class="d-flex justify-content-center">
                    <form method="post" class="text-center col-md-8 col-lg-8 col-xl-7"
                        action="{% url 'guest_reservation' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary btn-lg text-uppercase">Reserve</button>
                    </form>
                </div>
                <p class="text-center">Thank You for choosing our family restaurant!</p>
                {% if reservation_success %}
                <!-- Success Modal -->
                <div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="successModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title text-center" id="successModalLabel">Your reservation has been successful!
                                </h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body text-center">
                                <h6>Thank you for making a reservation. We look forward to serving you!</h6>
                                <p>Your reservation is for: {{ reservation_date}} at {{ reservation_time }}</p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-pimary" data-bs-dismiss="modal">Colse</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- target the Modal to show automaticaly -->
{% if reservation_success %}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var successModal = new bootstrap.Modal(document.getElementById('successModal'));
        successModal.show();

        var modalElement = document.getElementById('successModal');
        modalElement.addEventListener('hidden.bs.modal', function() {
            window.location.href = '{% url "index" %}';
        });
    });
</script> 
{% endif %}

<!-- guest_reservation.html content ends here -->
{% endblock %}

hello_alps/templates/hello_alps/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container-fluid p-0 welcome">
    <div class="row justify-content-center g-0 align-items-stretch">
        <div class="col-11 col-md-5 left-section p-0 m-0 d-flex flex-column align-items-stretch">
            <div class="d-flex justify-content-center align-items-center text-center mx-auto my-4 p-3 flex-grow-1">
                <h4 class="display-6">Immerse yourself in the vibrant essence of three continents with diverse cultures and the unifying embrace of One Love.</h4>
            </div>
            <div class="d-grid mb-2 p-0">
                <a href="{% url 'menu_list' %}" class="btn btn-light btn-lg text-uppercase p-0 m-0">Menu</a>
            </div>
        </div>
        <div class="col-11 col-md-7 right-section p-0 d-flex align-items-stretch">
            <div id="carouselExampleSlidesOnly" class="carousel slide w-100" data-bs-ride="carousel">
                <div class="carousel-inner h-100">
                    <div class="carousel-item">
                        <img src="{% static 'images/pizza.png' %}" class="d-block w-100 h-100"
                            alt="our home made pizza">
                    </div>
                    <div class="carousel-item active">
                        <img src="{% static 'images/garden.png' %}" class="d-block w-100 h-100"
                            alt="a picture of a cup of coffee">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/pizza3.png' %}" class="d-block w-100 h-100"
                            alt="the view of our garden">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/cofe.png' %}" class="d-block w-100 h-100"
                            alt="our home made pizza">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid p-0 welcome">
    <div class="row justify-content-center g-0 align-items-stretch">
        <div class="col-11 col-md-7 left-section p-0 d-flex align-items-stretch">
            <div id="carouselExampleSlidesOnly1" class="carousel slide w-100" data-bs-ride="carousel">
                <div class="carousel-inner h-100">
                    <div class="carousel-item active">
                        <img src="{% static 'images/alm.png' %}" class="d-block w-100 h-100"
                            alt="a picture of a cup of alm">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/river.png' %}" class="d-block w-100 h-100"
                            alt="the river">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/cow.png' %}" class="d-block w-100 h-100"
                            alt="beautifull cow">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-11 col-md-5 right-section p-0 m-0 d-flex flex-column align-items-stretch">
            <div class="d-flex justify-content-center align-items-center text-center mx-auto m-0 p-3 flex-grow-1">
                <h4 class="display-6">Nestled in the picturesque Alpbachtal Valley in Tirol, our restaurant offers a unique dining experience with breathtaking alpine scenery.</h4>
            </div>
            <div class="d-grid m-0 p-0">
                <a href="{% url 'contact' %}" class="btn btn-light btn-lg text-uppercase p-0 m-0">Contact</a>
            </div>
        </div>        
    </div>
</div>

<!-- Opening Hours Section -->
<div class="container-fluid p-0 welcome">
    <div class="row flex-row justify-content-center g-0 align-items-stretch">
        <div class="col-11 col-md-5 left-section  m-0 d-flex flex-column align-items-stretch ">
            <div class="opening-hours flex-column justify-content-center align-items-center mx-auto m-0 p-3 flex-grow-1 h-100">
                <h4 class="text-center display-6">Opening Hours</h4>
                <ul class="list-unstyled opening-hours-list">
                    {% for time in opening_hours %}
                    <li>
                        <strong>{{ time.get_day_of_week_display }}:</strong> {{ time.open_time|date:"H:i" }} :
                        {{ time.close_time|date:"H:i" }}
                    </li>
                    {% endfor %}
                </ul>
            </div> 
            <div class="d-grid m-0 p-0">
                <a href="{% url 'user_reservation' %}" class="btn btn-light btn-lg text-uppercase p-0 m-0">Make a Reservation</a>
            </div>           
        </div>
        <div class="col-11 col-md-7 right-section p-0 d-flex align-items-stretch">
            <div id="carouselExampleSlidesOnly2" class="carousel slide w-100" data-bs-ride="carousel">
                <div class="carousel-inner h-100">
                    <div class="carousel-item active">
                        <img src="{% static 'images/opening-hours1.jpg' %}" class="d-block w-100 h-100"
                            alt="a picture of a coocooc clock">
                    </div>                    
                </div>
            </div>
        </div>
    </div>
</div>
<hr>
<p class="text-center">Thank You for choosing our family restaurant!</p>

<!-- index.html content ends here -->
{% endblock %}

hello_alps/templates/hello_alps/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- login.html content starts here -->

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="login mt-5 mx-5">
                <h1 class="text-center">Log In</h1>
                <hr>
                <form method="post" class="text-center">
                    {% csrf_token %}
                    {{ form.as_p}}
                    <input type="hidden" name="next" value="{% url 'user_reservation' %}">
                    <button type="submit" class="btn btn-primary">Log In</button>
                </form>
                <p class="text-center">If you don't have an account, you can easily <a href="{% url 'signup_url' %}">Sign Up</a> here!</p>
            </div>
        </div>
    </div>
</div>

<!-- login.html content ends here -->
{% endblock %}

hello_alps/templates/hello_alps/menu_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="menu mt-5 mx-5">
                <h1 class="text-center">Menu</h1>
                <hr>
                {% for category, items in sort_menu_items.items %}
                <h3>{{ category|title }}</h3>
                <hr>
                <ul class="list-unstyled menu-list">
                    {% for item in items %}
                    <li>
                        {{ item.name|safe }} {{ item.description|safe }} {{ item.price }}€
                    </li>
                    {% endfor %}
                </ul>
                <hr>
                {% endfor %}
                <p class="text-center">Thank You for choosing our family restaurant!</p>
            </div>
        </div>
    </div>
</div>

<!-- menu_list.html content ends here -->
{% endblock %}

hello_alps/templates/hello_alps/register.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- login.html content starts here -->

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="login mt-5 mx-5 ">
                <h1 class="text-center">Register</h1>
                <hr>
                <div class="col-md-8 col-lg-7 col-xl-7 mx-auto">
                    <form method="post" class="text-center">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit" class="btn btn-primary">Register</button>
                    </form>
                </div>
                <p class="text-center">If you already have an account, you can easily <a
                        href="{% url 'login_url' %}">Log In</a> here!</p>
            </div>
        </div>
    </div>
</div>

<!-- login.html content ends here -->
{% endblock %}

hello_alps/templates/hello_alps/reservations.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- reservations.html content starts here -->

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            {% if user.is_authenticated %}
                <!-- Redirect logged-in users to the user_reservations page -->
                <script type="text/javascript">
                    window.location.href = "{% url 'user_reservations' %}";
            </script>
            {% else %}
            <!-- Button link Log in -->
            <div class="d-grid gap-2 mb-4">
                <a href="{% url 'login_url' %}" class="btn btn-primary btn-lg text-uppercase">Log In</a>
            </div>
            <!-- Button link Sign Up -->
            <div class="d-grid gap-2 mb-4">
                <a href="{% url 'signup_url' %}" class="btn btn-primary btn-lg text-uppercase">Register</a>
            </div>
             <!-- Button link Guest -->
             <div class="d-grid gap-2 mb-4">
                <a href="{% url 'guest_reservation' %}" class="btn btn-primary btn-lg text-uppercase">Continue as Guest</a>
            </div>
            {% endif %}
            <p class="text-center">Thank You for choosing our family restaurant!</p>
        </div>
    </div>
</div>

<!-- reservations.html content ends here -->
{% endblock %}

hello_alps/templates/hello_alps/user_reservation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<!-- user_reservation.html content starts here -->

<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="user_reservation mt-5 mx-5">
                <h1 class="text-center">Make a Reservation</h1>
                <hr>
                <div class="d-flex justify-content-center">
                    <form method="post" class="text-center col-md-8 col-lg-8 col-xl-7"
                        action="{% url 'user_reservation' %}">
                        {% csrf_token %}
                        {{ form.date|as_crispy_field }}
                        {{ form.time|as_crispy_field }}
                        {{ form.table|as_crispy_field }}
                        {{ form.comment|as_crispy_field }}
                        <button type="submit" class="btn btn-primary btn-lg text-uppercase">Reserve</button>
                    </form>
                </div>
                <p class="text-center">Thank You for choosing our family restaurant!</p>
            </div>
        </div>
    </div>
</div>

<!-- user_reservation.html content ends here -->
{% endblock %}